<a href="https://colab.research.google.com/github/Haritsukeru/Machine-Learn/blob/main/%22%D0%9B%D0%A0_1_%D0%93%D1%83%D0%BB%D0%B0%D0%BA_%D0%9A%D0%B8%D1%80%D0%B8%D0%BB%D0%BE_%D0%A4%D0%86%D0%A2_3_12_Numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

In [ ]:
#Був присутнім на парі

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [ ]:
# Код студента
import numpy as np
print(np.__version__)


2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [ ]:
# Код студента
arr = np.array([2, 4, 6, 8, 10])
print(arr)
print(type(arr))


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [ ]:
# Код студента
arr_nulls = np.zeros(10)
arr_ones = np.ones(8)
arr_seventh = np.full(6,7)

print(arr_nulls)
print(arr_ones)
print(arr_seventh)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [ ]:
# Код студента
arr = np.arange(1, 21)
even_arr = np.arange(2, 21, 2)

print(arr)
print(even_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [ ]:
# Код студента
arr_line = np.linspace(0, 1, 11)

print(arr_line)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [ ]:
# Код студента
arr1 = np.arange(1, 13)
matrix = arr1.reshape(3, 4)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [ ]:
# Код студента
arr1 = np.arange(1, 13)
matrix = arr1.reshape(3, 4)


print("ndim", np.ndim(matrix))
print("shape", np.shape(matrix))
print("size", np.size(matrix))
print("dtype", matrix.dtype)


ndim 2
shape (3, 4)
size 12
dtype int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [ ]:
# Код студента
arr_full = np.array([1.2, 3.5, 5.7, 7.9])
int_arr = arr_full.astype(int)

print(arr_full)
print(int_arr)

[1.2 3.5 5.7 7.9]
[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [ ]:
# Код студента
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("1.\n", arr[0])
print("2.\n", arr[-1])
print("3.\n", arr[2:6])
print("4.\n", arr[::2])

1.
 10
2.
 80
3.
 [30 40 50 60]
4.
 [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [ ]:
# Код студента
matrix = np.arange(1, 13).reshape(3, 4)
print(matrix)

print("1.\n", matrix[1, 2])
print("2.\n", matrix[1])
print("3.\n", matrix[:, 2])
print("4.\n", matrix[1:,  :2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1.
 7
2.
 [5 6 7 8]
3.
 [ 3  7 11]
4.
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [ ]:
# Код студента
arr = np.arange(1, 16)
arr[5:10] = 0

print(arr)

[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [ ]:
# Код студента
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [ ]:
# Код студента
arr = np.array([4, 8, 15, 16, 23, 42])

print(np.sum(arr))
print(np.average(arr))
print(np.min(arr))
print(np.max(arr))
print(np.median(arr))
print(np.std(arr))

108
18.0
4
42
15.5
12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [ ]:
# Код студента
matrix1 = np.arange(1, 10).reshape(3, 3)

print(np.sum(matrix1))
print(np.sum(matrix1, axis = 0))
print(np.sum(matrix1, axis = 1))
print(np.mean(matrix1, axis = 0))

45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [ ]:
# Код студента
arr = np.arange(1, 11)

print(np.square(arr))
print(np.sqrt(arr))
print(np.log(arr))

[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [ ]:
# Код студента
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print(arr[arr > 15])
print(arr[arr % 2 == 0])
print(arr[(arr >=10) & (arr <= 30)])

[18 21 25 30 34]
[12 18 30 34]
[12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])

arr[arr < 0] = 0

print(arr)

[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [ ]:
# Код студента
np.random.seed(42)

arr = np.random.randint(0, 101, size=20)
print(arr)

over49 = np.sum (arr > 50)
print(over49)

lessthan50 = np.sum(arr <= 50)
print(lessthan50)

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
12
8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [ ]:
# Код студента
arr = np.arange(1, 25)

matrix1 = arr.reshape(4, 6)
print(matrix1.shape)

matrix2 = arr.reshape(6, 4)
print(matrix2.shape)

matrix3 = arr.reshape(2,3,4)
print(matrix3.shape)

(4, 6)
(6, 4)
(2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [ ]:
# Код студента
A = np.array([[1, 2],
     [3, 4]])

B = np.array([[5, 6],
     [7, 8]])

vertical = np.vstack((A, B))
print(vertical)

horizontal = np.hstack((A,B))
print(horizontal)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [ ]:
# Код студента
matrix1 = np.arange(1,13).reshape(3, 4)

mflat = matrix1.flatten()
print(mflat)

mrave = matrix1.ravel()
print(mrave)

print(np.array_equal(mflat, mrave))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [ ]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)

print(a - b)

print(a * 3)
print(b * 3)

[ 3  7 11]
[1 1 1]
[ 6 12 18]
[ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [ ]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

cap1 = np.dot(a, b)
print(cap1)

cap2 = a @ b
print(cap2)

32
32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [ ]:
# Код студента
v = np.array([3,4])

normalv = np.linalg.norm(v)
print(normalv)

vnormalv = v / normalv
print(vnormalv)

print(np.linalg.norm(vnormalv))

5.0
[0.6 0.8]
1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [ ]:
# Код студента
a =  np.array([1, 0, 0])
b = np.array([0, 1, 0])
cross = np.cross(a, b)
print(cross)

[0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [ ]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])

dot = np.dot(a, b)
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)

cos = dot / (norm_a * norm_b)
print(cos)

angle1 = np.arccos(cos)
angledegree = np.degrees(angle1)
print(angledegree)

0.7999999999999998
36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6]])

trans = A.T
print(trans)

trans1 = np.transpose(A)
print(trans1)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [ ]:
# Код студента
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

lap = A * B
print(lap)

matmult = A @ B
print(matmult)

# * множить елемент на елемент в той час як @ є матричним множенням - стовпець на рядок

[[2 0]
 [3 8]]
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [ ]:
# Код студента
A = np.array([[4, 7],
              [2, 6]])

detA = np.linalg.det(A)
print(detA)

invA = np.linalg.inv(A)
print(invA)

check = A @ invA
print(check)

10.000000000000002
[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [ ]:
# Код студента
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

x = np.linalg.solve(A, b)
print(x)

[1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [ ]:
# Код студента
one = np.eye(4)
print(one)

randmat = np.random.randint(1, 10, size=(4, 4))
print(randmat)

result = randmat @ one
print(result)

equal = np.array_equal(randmat, result)
print(equal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[2 5 1 6]
 [9 1 3 7]
 [4 9 3 5]
 [3 7 5 9]]
[[2. 5. 1. 6.]
 [9. 1. 3. 7.]
 [4. 9. 3. 5.]
 [3. 7. 5. 9.]]
True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

result = A + 10

print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [ ]:
# Код студента
A = np.array([[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]])

v = np.array([10, 20, 30])

result = A + v
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [ ]:
# Код студента
A = np.array([[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]])

mean = np.mean(A, axis=0)

std = np.std(A, axis=0)

Anorm = (A - mean) / std
print(Anorm)

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [ ]:
# Код студента
np.random.seed(42)

arrint = np.random.randint(1, 101, size=10)
print(arrint)

randmat = np.random.rand(3, 3)
print(randmat)

normarr = np.random.normal(loc=0.0, scale=1.0, size=1000)

mean = np.mean(normarr)
std = np.std(normarr)

print(mean)
print(std)

[52 93 15 72 61 21 83 87 75 75]
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
0.02216865975826456
0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [ ]:
# Код студента
np.random.seed(42)

grades = np.random.randint(0, 101, size=30)
print(grades)

mean = np.mean(grades)
print(mean)

median = np.median(grades)
print(median)

max_grade = np.max(grades)
min_grade = np.min(grades)
print(max_grade)
print(min_grade)

c60 = np.sum(grades >= 60)
print(c60)

c90 = (np.sum(grades >= 90) / grades.size) * 100
print(f"{c90:.2f}%")

[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
50.86666666666667
54.5
99
1
13
6.67%


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [ ]:
# Код студента
sales = np.array([[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]])

prod = np.sum(sales, axis=1)
print(prod)

month = np.sum(sales, axis=0)
print(month)

bestprod = np.argmax(prod) + 1
print(bestprod)

bestmonth = np.argmax(month) + 1
print(bestmonth)

meanprod = np.mean(sales, axis=1)
print(meanprod)

[600 380 820]
[400 420 480 500]
3
4
[150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [ ]:
# Код студента
np.random.seed(42)

matrix = np.random.randint(1, 21, size=(5, 5))
print(matrix)

forward = np.sum(np.diag(matrix))
print(forward)

side = np.sum(np.diag(np.fliplr(matrix)))
print(side)

maxrow = np.max(matrix, axis=1)
print(maxrow)

minbar = np.min(matrix, axis=0)
print(minbar)

mean = np.mean(matrix)
print(mean)

matrix[matrix < mean] = 0
print(matrix)

[[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]
59
32
[20 19 12 17 19]
[ 2  1  2 11  4]
10.52
[[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [ ]:
# Код студента
X = np.array([[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]])

way1_2 = np.linalg.norm(X[0] - X[1])
print(way1_2)

way1_3 = np.linalg.norm(X[0] - X[2])
print(way1_3)

way2_3 = np.linalg.norm(X[1] - X[2])
print(way2_3)

1.7320508075688772
5.196152422706632
6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [ ]:
# Код студента
np.random.seed(42)

matrix = np.random.randint(1, 11, size=(4, 4))
print(matrix)

normal = np.linalg.norm(matrix, axis=1, keepdims=True)
print(normal)

matnormal = matrix / normal
print(matnormal)

print(np.linalg.norm(normal, axis=1))

[[ 7  4  8  5]
 [ 7 10  3  7]
 [ 8  5  4  8]
 [ 8  3  6  5]]
[[12.40967365]
 [14.38749457]
 [13.        ]
 [11.5758369 ]]
[[0.56407607 0.32232919 0.64465837 0.40291148]
 [0.48653363 0.69504805 0.20851441 0.48653363]
 [0.61538462 0.38461538 0.30769231 0.61538462]
 [0.69109474 0.25916053 0.51832106 0.43193421]]
[12.40967365 14.38749457 13.         11.5758369 ]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [ ]:
# Код студента
A = np.array([
    [1, 2 , 1],
    [2, 1, -1],
    [3, -1, 2]
])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
print(x)

checks = A @ x
print(checks)

equal = np.allclose(checks, b)
print(equal)

[ 2.22222222  3.44444444 -0.11111111]
[9. 8. 3.]
True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
